include:
  - board: nice_nano_v2
    # This is the correct shield name
    shield: splitkb_aurora_sofle_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: nice_nano_v2
    # This is the correct shield name
    shield: splitkb_aurora_sofle_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
