# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  - board: nice_nano_v2  # (Or your board name)
    shield: sofle_left   # (Or your shield name)
    snippet:
      - studio-rpc-usb-uart
      - oled # <-- THIS TURNS ON YOUR SCREENS
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_USB_HID=y # <-- THIS TURNS ON USB TYPING

  - board: nice_nano_v2  # (Or your board name)
    shield: sofle_right  # (Or your shield name)
    snippet:
      - studio-rpc-usb-uart
      - oled # <-- THIS TURNS ON YOUR SCREENS
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_USB_HID=y # <-- THIS TURNS ON USB TYPING