include:
  - board: nice_nano_v2
    # This combines the key layout, the adapter, and the screen
    shield: splitkb_aurora_sofle_left nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: nice_nano_v2
    # This combines the key layout, the adapter, and the screen
    shield: splitkb_aurora_sofle_right nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
